export interface Product {
  id: string
  name: string
  brand: string
  category: string
  price: number
  oldPrice?: number
  description: string
  specs: Record<string, string>
  inStock: boolean
  featured: boolean
  image: string
}

export const categories = [
  'Visseuses / Perceuses',
  'Meuleuses',
  'Scies',
  'Outillage à main',
  'Mesure / Niveau',
  'Accessoires',
]

export const products: Product[] = [
  // === VISSEUSES / PERCEUSES ===
  { id: '1', name: 'Perceuse-visseuse DCD791D2 20V MAX XR', brand: 'dewalt', category: 'Visseuses / Perceuses', price: 289, oldPrice: 329, description: 'Perceuse-visseuse brushless compacte et légère. Idéale pour les travaux courants du BTP.', specs: { 'Tension': '20V', 'Couple max': '70 Nm', 'Mandrin': '13 mm', 'Poids': '1.6 kg' }, inStock: true, featured: true, image: 'https://placehold.co/400x400/1a1a2e/FFCC00?text=DCD791' },
  { id: '2', name: 'Perceuse à percussion DCD996P2 20V MAX XR', brand: 'dewalt', category: 'Visseuses / Perceuses', price: 379, description: 'Perceuse à percussion 3 vitesses haute performance pour le béton et la maçonnerie.', specs: { 'Tension': '20V', 'Couple max': '95 Nm', 'Vitesse': '0-2000 tr/min', 'Mandrin': '13 mm' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFCC00?text=DCD996' },
  { id: '3', name: 'Visseuse à chocs DCF887D2 20V MAX XR', brand: 'dewalt', category: 'Visseuses / Perceuses', price: 259, description: 'Visseuse à chocs brushless compacte avec 3 vitesses et mode précision.', specs: { 'Tension': '20V', 'Couple max': '205 Nm', 'Vitesse': '0-3250 tr/min', 'Poids': '0.9 kg' }, inStock: true, featured: true, image: 'https://placehold.co/400x400/1a1a2e/FFCC00?text=DCF887' },
  { id: '4', name: 'Perceuse-visseuse M18 FDD2-502X FUEL', brand: 'milwaukee', category: 'Visseuses / Perceuses', price: 349, oldPrice: 399, description: 'Perceuse-visseuse FUEL brushless avec système REDLINK PLUS pour une protection optimale.', specs: { 'Tension': '18V', 'Couple max': '135 Nm', 'Mandrin': '13 mm', 'Poids': '1.7 kg' }, inStock: true, featured: true, image: 'https://placehold.co/400x400/1a1a2e/DB0032?text=M18+FDD2' },
  { id: '5', name: 'Visseuse à chocs M18 FID2-502X FUEL', brand: 'milwaukee', category: 'Visseuses / Perceuses', price: 319, description: 'Visseuse à chocs FUEL la plus compacte de sa catégorie avec 4 modes de couple.', specs: { 'Tension': '18V', 'Couple max': '226 Nm', 'Vitesse': '0-3600 tr/min', 'Poids': '1.1 kg' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/DB0032?text=M18+FID2' },
  { id: '6', name: 'Perceuse-visseuse DDF487RTJ 18V LXT', brand: 'makita', category: 'Visseuses / Perceuses', price: 269, description: 'Perceuse-visseuse brushless ultra-compacte avec boîtier MAKPAC.', specs: { 'Tension': '18V', 'Couple max': '40 Nm', 'Mandrin': '13 mm', 'Poids': '1.5 kg' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/00A7E1?text=DDF487' },
  { id: '7', name: 'Perceuse à percussion DHP486RTJ 18V LXT', brand: 'makita', category: 'Visseuses / Perceuses', price: 329, description: 'Perceuse à percussion brushless puissante avec variateur de vitesse.', specs: { 'Tension': '18V', 'Couple max': '130 Nm', 'Frappe': '0-27000 cps/min', 'Mandrin': '13 mm' }, inStock: true, featured: true, image: 'https://placehold.co/400x400/1a1a2e/00A7E1?text=DHP486' },
  { id: '8', name: 'Visseuse plaquiste DFS452Z 18V LXT', brand: 'makita', category: 'Visseuses / Perceuses', price: 189, description: 'Visseuse pour plaque de plâtre avec embrayage silencieux et nez ajustable.', specs: { 'Tension': '18V', 'Vitesse': '0-4000 tr/min', 'Poids': '1.6 kg', 'Profondeur': 'Réglable' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/00A7E1?text=DFS452' },
  { id: '9', name: 'Perforateur SDS-Plus M18 CHX FUEL', brand: 'milwaukee', category: 'Visseuses / Perceuses', price: 459, oldPrice: 519, description: 'Perforateur SDS-Plus FUEL 2.5J pour le perçage et le burinage dans le béton.', specs: { 'Tension': '18V', 'Énergie': '2.5 J', 'Perçage béton': '26 mm', 'Poids': '3.1 kg' }, inStock: true, featured: true, image: 'https://placehold.co/400x400/1a1a2e/DB0032?text=M18+CHX' },
  { id: '10', name: 'Perforateur DCH273P2 SDS-Plus 20V MAX', brand: 'dewalt', category: 'Visseuses / Perceuses', price: 429, description: 'Perforateur SDS-Plus brushless 3 modes avec absorbeur de vibrations.', specs: { 'Tension': '20V', 'Énergie': '2.1 J', 'Perçage béton': '24 mm', 'Poids': '3.0 kg' }, inStock: false, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFCC00?text=DCH273' },

  // === MEULEUSES ===
  { id: '11', name: 'Meuleuse 125mm DCG405N 20V MAX XR', brand: 'dewalt', category: 'Meuleuses', price: 199, description: 'Meuleuse brushless 125mm avec frein électronique et démarrage progressif.', specs: { 'Disque': '125 mm', 'Tension': '20V', 'Vitesse': '9000 tr/min', 'Poids': '1.75 kg' }, inStock: true, featured: true, image: 'https://placehold.co/400x400/1a1a2e/FFCC00?text=DCG405' },
  { id: '12', name: 'Meuleuse 125mm M18 FHSAG125XB FUEL', brand: 'milwaukee', category: 'Meuleuses', price: 249, description: 'Meuleuse FUEL 125mm avec frein FIXTEC et système anti-vibrations.', specs: { 'Disque': '125 mm', 'Tension': '18V', 'Vitesse': '8500 tr/min', 'Poids': '2.2 kg' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/DB0032?text=FHSAG125' },
  { id: '13', name: 'Meuleuse 125mm DGA513Z 18V LXT', brand: 'makita', category: 'Meuleuses', price: 179, description: 'Meuleuse brushless 125mm avec technologie anti-redémarrage AFT.', specs: { 'Disque': '125 mm', 'Tension': '18V', 'Vitesse': '8500 tr/min', 'Poids': '2.5 kg' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/00A7E1?text=DGA513' },
  { id: '14', name: 'Meuleuse 230mm DCG200 FLEXVOLT 54V', brand: 'dewalt', category: 'Meuleuses', price: 399, oldPrice: 449, description: 'Meuleuse 230mm FLEXVOLT sans fil pour coupes profondes.', specs: { 'Disque': '230 mm', 'Tension': '54V', 'Vitesse': '6000 tr/min', 'Poids': '3.5 kg' }, inStock: true, featured: true, image: 'https://placehold.co/400x400/1a1a2e/FFCC00?text=DCG200' },
  { id: '15', name: 'Meuleuse 125mm L 1710 FRA', brand: 'flex', category: 'Meuleuses', price: 159, description: 'Meuleuse filaire 1400W avec démarrage progressif et frein moteur.', specs: { 'Puissance': '1400 W', 'Disque': '125 mm', 'Vitesse': '11000 tr/min', 'Poids': '2.1 kg' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FF6600?text=L1710' },
  { id: '16', name: 'Meuleuse 150mm PE 150 18.0-EC', brand: 'flex', category: 'Meuleuses', price: 279, description: 'Polisseuse rotative 150mm sans fil 18V pour les finitions parfaites.', specs: { 'Tension': '18V', 'Disque': '150 mm', 'Vitesse': '800-2100 tr/min', 'Poids': '2.3 kg' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FF6600?text=PE150' },
  { id: '17', name: 'Meuleuse 125mm M18 CAG125X', brand: 'milwaukee', category: 'Meuleuses', price: 169, description: 'Meuleuse compacte 125mm avec carter de protection réglable.', specs: { 'Disque': '125 mm', 'Tension': '18V', 'Vitesse': '8500 tr/min', 'Poids': '2.0 kg' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/DB0032?text=CAG125' },
  { id: '18', name: 'Meuleuse 125mm GA5090 1900W', brand: 'makita', category: 'Meuleuses', price: 219, description: 'Meuleuse filaire 1900W haute puissance avec interrupteur à palette.', specs: { 'Puissance': '1900 W', 'Disque': '125 mm', 'Vitesse': '11000 tr/min', 'Poids': '2.5 kg' }, inStock: false, featured: false, image: 'https://placehold.co/400x400/1a1a2e/00A7E1?text=GA5090' },

  // === SCIES ===
  { id: '19', name: 'Scie circulaire DCS578T2 FLEXVOLT 54V', brand: 'dewalt', category: 'Scies', price: 499, oldPrice: 559, description: 'Scie circulaire FLEXVOLT 190mm sans fil, puissance équivalente au filaire.', specs: { 'Tension': '54V', 'Lame': '190 mm', 'Profondeur coupe': '61 mm', 'Poids': '3.7 kg' }, inStock: true, featured: true, image: 'https://placehold.co/400x400/1a1a2e/FFCC00?text=DCS578' },
  { id: '20', name: 'Scie plongeante TS 55 REBQ-Plus', brand: 'festool', category: 'Scies', price: 679, description: 'Scie plongeante de précision avec rail de guidage pour des coupes parfaites.', specs: { 'Puissance': '1200 W', 'Lame': '160 mm', 'Profondeur coupe': '55 mm', 'Poids': '4.5 kg' }, inStock: true, featured: true, image: 'https://placehold.co/400x400/1a1a2e/14532d?text=TS55' },
  { id: '21', name: 'Scie sauteuse DCS334N 20V MAX XR', brand: 'dewalt', category: 'Scies', price: 229, description: 'Scie sauteuse brushless avec poignée champignon pour un contrôle optimal.', specs: { 'Tension': '20V', 'Course': '26 mm', 'Coupe bois': '135 mm', 'Poids': '2.1 kg' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFCC00?text=DCS334' },
  { id: '22', name: 'Scie sabre DJR187Z 18V LXT', brand: 'makita', category: 'Scies', price: 199, description: 'Scie sabre sans fil pour la démolition et les coupes en plongée.', specs: { 'Tension': '18V', 'Course': '32 mm', 'Coupe bois': '255 mm', 'Poids': '3.6 kg' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/00A7E1?text=DJR187' },
  { id: '23', name: 'Scie circulaire DSS611Z 18V LXT', brand: 'makita', category: 'Scies', price: 169, description: 'Scie circulaire compacte 165mm idéale pour les charpentiers.', specs: { 'Tension': '18V', 'Lame': '165 mm', 'Profondeur coupe': '57 mm', 'Poids': '3.3 kg' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/00A7E1?text=DSS611' },
  { id: '24', name: 'Scie sauteuse PSC 420 HPC EBQ', brand: 'festool', category: 'Scies', price: 589, description: 'Scie sauteuse pendulaire de précision avec système FastFix.', specs: { 'Puissance': '550 W', 'Course': '23 mm', 'Coupe bois': '120 mm', 'Poids': '2.6 kg' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/14532d?text=PSC420' },
  { id: '25', name: 'Scie sabre M18 FSZ FUEL', brand: 'milwaukee', category: 'Scies', price: 259, description: 'Scie sabre FUEL avec technologie QUIK-LOK pour changement de lame rapide.', specs: { 'Tension': '18V', 'Course': '32 mm', 'Coupe bois': '300 mm', 'Poids': '3.4 kg' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/DB0032?text=M18+FSZ' },
  { id: '26', name: 'Scie circulaire DWE575K 1600W', brand: 'dewalt', category: 'Scies', price: 189, description: 'Scie circulaire filaire légère 190mm avec guide laser intégré.', specs: { 'Puissance': '1600 W', 'Lame': '190 mm', 'Profondeur coupe': '67 mm', 'Poids': '4.0 kg' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFCC00?text=DWE575' },

  // === OUTILLAGE À MAIN ===
  { id: '27', name: 'Coffret clés mixtes 440 12 pièces', brand: 'facom', category: 'Outillage à main', price: 149, description: 'Coffret de 12 clés mixtes OGV en acier chrome-vanadium, finition satinée.', specs: { 'Tailles': '8-19 mm', 'Nombre': '12 pièces', 'Matière': 'Chrome-vanadium', 'Finition': 'Satinée' }, inStock: true, featured: true, image: 'https://placehold.co/400x400/1a1a2e/E63946?text=Facom+440' },
  { id: '28', name: 'Coffret douilles 1/2" SL.161 25 pièces', brand: 'facom', category: 'Outillage à main', price: 219, oldPrice: 259, description: 'Coffret complet de douilles 1/2 pouce avec cliquet rotatif.', specs: { 'Carré': '1/2"', 'Nombre': '25 pièces', 'Tailles': '10-32 mm', 'Cliquet': '72 dents' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/E63946?text=SL161' },
  { id: '29', name: 'Jeu tournevis Kraftform Kompakt 25', brand: 'wera', category: 'Outillage à main', price: 45, description: 'Tournevis compact avec 6 embouts interchangeables Rapidaptor.', specs: { 'Embouts': '6 pièces', 'Type': 'PH, PZ, TX', 'Manche': 'Kraftform', 'Rangement': 'Intégré' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/78BE20?text=Kompakt+25' },
  { id: '30', name: 'Jeu clés mâles Hex-Plus 950/9 SM', brand: 'wera', category: 'Outillage à main', price: 39, description: 'Jeu de 9 clés mâles avec finition BlackLaser anti-corrosion.', specs: { 'Tailles': '1.5-10 mm', 'Nombre': '9 pièces', 'Finition': 'BlackLaser', 'Support': 'Clip intégré' }, inStock: true, featured: true, image: 'https://placehold.co/400x400/1a1a2e/78BE20?text=950+SM' },
  { id: '31', name: 'Pince multiprise Cobra 250mm', brand: 'facom', category: 'Outillage à main', price: 35, description: 'Pince multiprise à crémaillère avec mâchoires auto-ajustables.', specs: { 'Longueur': '250 mm', 'Ouverture': '46 mm', 'Matière': 'Chrome-vanadium', 'Poignées': 'Bi-matière' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/E63946?text=Cobra' },
  { id: '32', name: 'Marteau arrache-clou FatMax 570g', brand: 'stanley', category: 'Outillage à main', price: 32, description: 'Marteau monobloc anti-vibrations avec manche graphite.', specs: { 'Poids tête': '570 g', 'Longueur': '340 mm', 'Type': 'Arrache-clou', 'Manche': 'Graphite' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFC107?text=FatMax' },
  { id: '33', name: 'Cutter FatMax 25mm', brand: 'stanley', category: 'Outillage à main', price: 19, description: 'Cutter professionnel à lame sécable 25mm avec corps bi-matière.', specs: { 'Lame': '25 mm', 'Type': 'Sécable', 'Corps': 'Bi-matière', 'Blocage': 'À vis' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFC107?text=Cutter' },
  { id: '34', name: 'Jeu tournevis Joker 6003 Set 1', brand: 'wera', category: 'Outillage à main', price: 89, oldPrice: 99, description: 'Ensemble de clés à fourche Joker avec fonction de maintien intégrée.', specs: { 'Tailles': '10-19 mm', 'Nombre': '6 pièces', 'Fonction': 'Maintien intégré', 'Finition': 'Chrome' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/78BE20?text=Joker+6003' },
  { id: '35', name: 'Pince coupante diagonale 180mm', brand: 'facom', category: 'Outillage à main', price: 29, description: 'Pince coupante de précision pour fils durs et semi-durs.', specs: { 'Longueur': '180 mm', 'Coupe': 'Fils durs', 'Matière': 'Acier spécial', 'Poignées': 'Gainées' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/E63946?text=Diagonale' },
  { id: '36', name: 'Coffret outils 145 pièces', brand: 'stanley', category: 'Outillage à main', price: 159, description: 'Coffret complet de 145 outils pour le professionnel polyvalent.', specs: { 'Nombre': '145 pièces', 'Contenu': 'Clés, douilles, embouts', 'Coffret': 'Métallique', 'Garantie': 'À vie' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFC107?text=Coffret+145' },

  // === MESURE / NIVEAU ===
  { id: '37', name: 'Niveau digital 196-2 Electronic IP65 60cm', brand: 'stabila', category: 'Mesure / Niveau', price: 189, description: 'Niveau à bulle digital avec affichage des angles et protection IP65.', specs: { 'Longueur': '60 cm', 'Précision': '0.5 mm/m', 'Digital': 'Oui', 'Protection': 'IP65' }, inStock: true, featured: true, image: 'https://placehold.co/400x400/1a1a2e/FFD700?text=196-2' },
  { id: '38', name: 'Niveau magnétique Type 70M 120cm', brand: 'stabila', category: 'Mesure / Niveau', price: 89, description: 'Niveau à bulle professionnel avec aimants intégrés pour structures métalliques.', specs: { 'Longueur': '120 cm', 'Précision': '0.5 mm/m', 'Fioles': '3', 'Magnétique': 'Oui' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFD700?text=Type+70M' },
  { id: '39', name: 'Niveau Pocket Electric 7cm', brand: 'stabila', category: 'Mesure / Niveau', price: 25, description: 'Mini niveau de poche pour électriciens avec clip de fixation.', specs: { 'Longueur': '7 cm', 'Précision': '1 mm/m', 'Fioles': '1', 'Clip': 'Oui' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFD700?text=Pocket' },
  { id: '40', name: 'Mètre ruban FatMax 8m x 32mm', brand: 'stanley', category: 'Mesure / Niveau', price: 29, description: 'Mètre ruban professionnel BladeArmor avec crochet magnétique.', specs: { 'Longueur': '8 m', 'Largeur': '32 mm', 'Crochet': 'Magnétique', 'Revêtement': 'BladeArmor' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFC107?text=FatMax+8m' },
  { id: '41', name: 'Télémètre laser TLM165S 50m', brand: 'stanley', category: 'Mesure / Niveau', price: 109, oldPrice: 129, description: 'Télémètre laser Bluetooth avec application smartphone pour plans.', specs: { 'Portée': '50 m', 'Précision': '±1.5 mm', 'Bluetooth': 'Oui', 'Fonctions': 'Surface, volume' }, inStock: true, featured: true, image: 'https://placehold.co/400x400/1a1a2e/FFC107?text=TLM165S' },
  { id: '42', name: 'Niveau laser rotatif LAR 160 G', brand: 'stabila', category: 'Mesure / Niveau', price: 789, description: 'Niveau laser rotatif vert auto-nivelant pour chantiers extérieurs.', specs: { 'Portée': '160 m', 'Couleur laser': 'Vert', 'Auto-nivelant': 'Oui', 'Protection': 'IP65' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFD700?text=LAR160G' },
  { id: '43', name: 'Niveau Type 196-2 200cm', brand: 'stabila', category: 'Mesure / Niveau', price: 79, description: 'Niveau à bulle 200cm en aluminium pour travaux de maçonnerie.', specs: { 'Longueur': '200 cm', 'Précision': '0.5 mm/m', 'Fioles': '3', 'Matière': 'Aluminium' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFD700?text=196-2+200' },
  { id: '44', name: 'Mètre ruban STHT0-36121 5m', brand: 'stanley', category: 'Mesure / Niveau', price: 15, description: 'Mètre ruban compact 5m avec boîtier anti-chocs.', specs: { 'Longueur': '5 m', 'Largeur': '19 mm', 'Boîtier': 'Anti-chocs', 'Blocage': 'Manuel' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFC107?text=5m' },

  // === ACCESSOIRES ===
  { id: '45', name: 'Batterie DCB205 20V MAX XR 5.0Ah', brand: 'dewalt', category: 'Accessoires', price: 99, oldPrice: 119, description: 'Batterie lithium-ion 5.0Ah compatible avec toute la gamme 20V MAX.', specs: { 'Tension': '20V', 'Capacité': '5.0 Ah', 'Type': 'Li-Ion', 'Jauge': 'LED 3 niveaux' }, inStock: true, featured: true, image: 'https://placehold.co/400x400/1a1a2e/FFCC00?text=DCB205' },
  { id: '46', name: 'Batterie M18 HB12 HIGH OUTPUT 12.0Ah', brand: 'milwaukee', category: 'Accessoires', price: 199, description: 'Batterie haute capacité 12.0Ah pour les applications les plus exigeantes.', specs: { 'Tension': '18V', 'Capacité': '12.0 Ah', 'Type': 'Li-Ion', 'Compatible': 'M18' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/DB0032?text=HB12' },
  { id: '47', name: 'Chargeur rapide DCB118 20V/60V', brand: 'dewalt', category: 'Accessoires', price: 69, description: 'Chargeur rapide ventilé compatible 20V et 60V FLEXVOLT.', specs: { 'Compatibilité': '20V / 60V', 'Temps charge': '60 min (5Ah)', 'Ventilé': 'Oui', 'LED': 'Indicateur état' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFCC00?text=DCB118' },
  { id: '48', name: 'Batterie BL1850B 18V 5.0Ah', brand: 'makita', category: 'Accessoires', price: 89, description: 'Batterie Makita Star avec indicateur de charge LED intégré.', specs: { 'Tension': '18V', 'Capacité': '5.0 Ah', 'Type': 'Li-Ion', 'Protection': 'Surcharge' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/00A7E1?text=BL1850B' },
  { id: '49', name: 'Coffret TSTAK DWST1-71195', brand: 'dewalt', category: 'Accessoires', price: 45, description: 'Coffret de transport empilable système TSTAK avec mousse personnalisable.', specs: { 'Dimensions': '440x332x145 mm', 'Empilable': 'Oui', 'Mousse': 'Personnalisable', 'Verrous': 'Latéraux' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFCC00?text=TSTAK' },
  { id: '50', name: 'Coffret MAKPAC Taille 3', brand: 'makita', category: 'Accessoires', price: 39, description: 'Coffret de transport empilable MAKPAC avec intérieur modulable.', specs: { 'Dimensions': '395x295x210 mm', 'Empilable': 'Oui', 'Système': 'MAKPAC', 'Verrous': 'Clips' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/00A7E1?text=MAKPAC' },
  { id: '51', name: 'Chargeur rapide M12-M18 C18B6', brand: 'milwaukee', category: 'Accessoires', price: 119, description: 'Chargeur séquentiel 6 postes pour batteries M12 et M18.', specs: { 'Compatibilité': 'M12 / M18', 'Postes': '6', 'Séquentiel': 'Oui', 'LED': '3 niveaux' }, inStock: false, featured: false, image: 'https://placehold.co/400x400/1a1a2e/DB0032?text=C18B6' },
  { id: '52', name: 'Set 32 embouts Impact Torsion', brand: 'dewalt', category: 'Accessoires', price: 25, description: 'Set de 32 embouts de vissage Impact Torsion pour visseuses à chocs.', specs: { 'Nombre': '32 pièces', 'Type': 'PH, PZ, TX, Hex', 'Résistance': 'Impact', 'Boîtier': 'Compact' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFCC00?text=Impact+32' },
  { id: '53', name: 'Aspirateur DWV902M classe M', brand: 'dewalt', category: 'Accessoires', price: 449, description: 'Aspirateur de chantier classe M avec décolmatage automatique du filtre.', specs: { 'Capacité': '38 L', 'Puissance': '1400 W', 'Classe': 'M', 'Décolmatage': 'Auto' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFCC00?text=DWV902M' },
  { id: '54', name: 'Lampe LED DCL074 20V MAX', brand: 'dewalt', category: 'Accessoires', price: 129, description: 'Lampe de chantier LED 5000 lumens avec trépied intégré.', specs: { 'Lumens': '5000', 'Tension': '20V', 'Modes': '3', 'Trépied': 'Intégré' }, inStock: true, featured: false, image: 'https://placehold.co/400x400/1a1a2e/FFCC00?text=DCL074' },
]
