export interface Product {
  id: string
  name: string
  brand: string
  category: string
  price: number
  oldPrice?: number
  description: string
  specs: Record<string, string>
  inStock: boolean
  featured: boolean
  image: string
}

export const categories = [
  'Visseuses / Perceuses',
  'Meuleuses',
  'Scies',
  'Outillage à main',
  'Mesure / Niveau',
  'Accessoires',
]

function img(name: string, color: string): string {
  return `https://placehold.co/400x400/${color.replace('#', '')}/${encodeURIComponent('fff')}?text=${encodeURIComponent(name)}`
}

export const products: Product[] = [
  // ── Visseuses / Perceuses ──
  { id: '1', name: 'DCD999 Perceuse-visseuse 18V XR', brand: 'dewalt', category: 'Visseuses / Perceuses', price: 389, oldPrice: 449, description: 'Perceuse-visseuse brushless 18V FLEXVOLT Advantage. Puissance et endurance pour les travaux les plus exigeants.', specs: { 'Tension': '18V', 'Couple max': '126 Nm', 'Mandrin': '13 mm', 'Poids': '2.1 kg' }, inStock: true, featured: true, image: img('DCD999', '#FFCC00') },
  { id: '2', name: 'DCD796 Perceuse à percussion 18V', brand: 'dewalt', category: 'Visseuses / Perceuses', price: 259, description: 'Perceuse à percussion compacte brushless. Idéale pour le perçage bois, métal et maçonnerie.', specs: { 'Tension': '18V', 'Couple max': '70 Nm', 'Mandrin': '13 mm', 'Vitesse': '0-2000 tr/min' }, inStock: true, featured: false, image: img('DCD796', '#FFCC00') },
  { id: '3', name: 'M18 FPD3 Perceuse à percussion FUEL', brand: 'milwaukee', category: 'Visseuses / Perceuses', price: 419, oldPrice: 479, description: 'Perceuse à percussion 18V FUEL de 4ème génération. La plus puissante de sa catégorie.', specs: { 'Tension': '18V', 'Couple max': '158 Nm', 'Mandrin': '13 mm', 'Poids': '1.8 kg' }, inStock: true, featured: true, image: img('M18+FPD3', '#DB0032') },
  { id: '4', name: 'M18 FID3 Visseuse à chocs FUEL', brand: 'milwaukee', category: 'Visseuses / Perceuses', price: 349, description: 'Visseuse à chocs compacte FUEL avec 4 modes de vissage. Contrôle total sur chaque application.', specs: { 'Tension': '18V', 'Couple max': '226 Nm', 'Emmanchement': '1/4"', 'Poids': '1.5 kg' }, inStock: true, featured: false, image: img('M18+FID3', '#DB0032') },
  { id: '5', name: 'DHP486 Perceuse à percussion 18V LXT', brand: 'makita', category: 'Visseuses / Perceuses', price: 299, description: 'Perceuse à percussion brushless 18V avec technologie anti-vibration AVT.', specs: { 'Tension': '18V', 'Couple max': '130 Nm', 'Mandrin': '13 mm', 'Vitesse': '0-2100 tr/min' }, inStock: true, featured: true, image: img('DHP486', '#00A7E1') },
  { id: '6', name: 'DTD172 Visseuse à chocs 18V', brand: 'makita', category: 'Visseuses / Perceuses', price: 279, description: 'Visseuse à chocs compacte 18V LXT avec 4 vitesses et mode assist.', specs: { 'Tension': '18V', 'Couple max': '180 Nm', 'Emmanchement': '1/4"', 'Poids': '1.3 kg' }, inStock: true, featured: false, image: img('DTD172', '#00A7E1') },
  { id: '7', name: 'DCF850 Visseuse à chocs 18V ATOMIC', brand: 'dewalt', category: 'Visseuses / Perceuses', price: 229, description: 'Visseuse à chocs ultra-compacte série ATOMIC pour les espaces restreints.', specs: { 'Tension': '18V', 'Couple max': '203 Nm', 'Emmanchement': '1/4"', 'Longueur': '116 mm' }, inStock: true, featured: false, image: img('DCF850', '#FFCC00') },
  { id: '8', name: 'M12 FPD2 Perceuse à percussion M12', brand: 'milwaukee', category: 'Visseuses / Perceuses', price: 219, oldPrice: 259, description: 'Perceuse sous-compacte M12 FUEL parfaite pour les travaux légers et les accès difficiles.', specs: { 'Tension': '12V', 'Couple max': '44 Nm', 'Mandrin': '10 mm', 'Poids': '1.1 kg' }, inStock: true, featured: false, image: img('M12+FPD2', '#DB0032') },
  { id: '9', name: 'DDF484 Perceuse-visseuse 18V', brand: 'makita', category: 'Visseuses / Perceuses', price: 269, description: 'Perceuse-visseuse brushless compacte et légère pour un usage quotidien professionnel.', specs: { 'Tension': '18V', 'Couple max': '54 Nm', 'Mandrin': '13 mm', 'Poids': '1.6 kg' }, inStock: false, featured: false, image: img('DDF484', '#00A7E1') },

  // ── Meuleuses ──
  { id: '10', name: 'DCG409 Meuleuse 125mm 18V FLEXVOLT', brand: 'dewalt', category: 'Meuleuses', price: 339, oldPrice: 389, description: 'Meuleuse angulaire 125mm brushless avec frein électronique et embrayage anti-retour.', specs: { 'Disque': '125 mm', 'Tension': '18V', 'Vitesse': '9000 tr/min', 'Poids': '2.4 kg' }, inStock: true, featured: true, image: img('DCG409', '#FFCC00') },
  { id: '11', name: 'M18 FHSAG125 Meuleuse FUEL 125mm', brand: 'milwaukee', category: 'Meuleuses', price: 369, description: 'Meuleuse angulaire haute performance avec interrupteur à palette et démarrage progressif.', specs: { 'Disque': '125 mm', 'Tension': '18V', 'Vitesse': '8500 tr/min', 'Poids': '2.2 kg' }, inStock: true, featured: true, image: img('M18+FHSAG', '#DB0032') },
  { id: '12', name: 'DGA513 Meuleuse 125mm 18V LXT', brand: 'makita', category: 'Meuleuses', price: 289, description: 'Meuleuse angulaire brushless avec technologie AFT et SJS pour une sécurité maximale.', specs: { 'Disque': '125 mm', 'Tension': '18V', 'Vitesse': '8500 tr/min', 'Poids': '2.5 kg' }, inStock: true, featured: false, image: img('DGA513', '#00A7E1') },
  { id: '13', name: 'L 125 18.0 Meuleuse FLEX 125mm', brand: 'flex', category: 'Meuleuses', price: 319, description: 'Meuleuse angulaire 18V avec système de freinage rapide et protection anti-redémarrage.', specs: { 'Disque': '125 mm', 'Tension': '18V', 'Vitesse': '9000 tr/min', 'Poids': '2.3 kg' }, inStock: true, featured: false, image: img('L125+FLEX', '#FF6600') },
  { id: '14', name: 'DCG405 Meuleuse 125mm 18V XR', brand: 'dewalt', category: 'Meuleuses', price: 269, description: 'Meuleuse compacte brushless avec débrayage électronique et carter de protection.', specs: { 'Disque': '125 mm', 'Tension': '18V', 'Vitesse': '9000 tr/min', 'Poids': '1.75 kg' }, inStock: true, featured: false, image: img('DCG405', '#FFCC00') },
  { id: '15', name: 'M18 FHSAG125XB Meuleuse freinage', brand: 'milwaukee', category: 'Meuleuses', price: 399, description: 'Meuleuse angulaire FUEL avec le freinage le plus rapide du marché et interrupteur paddle.', specs: { 'Disque': '125 mm', 'Tension': '18V', 'Vitesse': '8500 tr/min', 'Freinage': '< 2s' }, inStock: true, featured: false, image: img('FHSAG125XB', '#DB0032') },
  { id: '16', name: 'DGA518 Meuleuse 125mm 2x18V', brand: 'makita', category: 'Meuleuses', price: 359, description: 'Meuleuse angulaire alimentée par 2 batteries 18V pour une puissance équivalente au filaire.', specs: { 'Disque': '125 mm', 'Tension': '2x18V', 'Vitesse': '8500 tr/min', 'Poids': '2.7 kg' }, inStock: false, featured: false, image: img('DGA518', '#00A7E1') },
  { id: '17', name: 'L 150 18.0 Meuleuse FLEX 150mm', brand: 'flex', category: 'Meuleuses', price: 379, oldPrice: 429, description: 'Meuleuse grand diamètre pour les découpes profondes et le travail de la pierre.', specs: { 'Disque': '150 mm', 'Tension': '18V', 'Vitesse': '7500 tr/min', 'Poids': '2.8 kg' }, inStock: true, featured: false, image: img('L150+FLEX', '#FF6600') },

  // ── Scies ──
  { id: '18', name: 'DCS578 Scie circulaire 190mm FLEXVOLT', brand: 'dewalt', category: 'Scies', price: 449, oldPrice: 499, description: 'Scie circulaire 54V brushless capable de couper des chevrons en un seul passage.', specs: { 'Lame': '190 mm', 'Tension': '54V', 'Profondeur': '61 mm', 'Vitesse': '5800 tr/min' }, inStock: true, featured: true, image: img('DCS578', '#FFCC00') },
  { id: '19', name: 'TS 55 FEBQ Scie plongeante Festool', brand: 'festool', category: 'Scies', price: 799, description: 'Scie plongeante de référence avec rail de guidage. Précision absolue pour les coupes droites.', specs: { 'Lame': '160 mm', 'Puissance': '1200W', 'Profondeur': '55 mm', 'Poids': '4.5 kg' }, inStock: true, featured: true, image: img('TS55', '#14532d') },
  { id: '20', name: 'DHS780 Scie circulaire 2x18V', brand: 'makita', category: 'Scies', price: 529, description: 'Scie circulaire 2x18V avec lame 305mm pour les coupes de grande section.', specs: { 'Lame': '305 mm', 'Tension': '2x18V', 'Profondeur': '91.5 mm', 'Vitesse': '6000 tr/min' }, inStock: true, featured: false, image: img('DHS780', '#00A7E1') },
  { id: '21', name: 'DCS334 Scie sauteuse 18V XR', brand: 'dewalt', category: 'Scies', price: 289, description: 'Scie sauteuse brushless avec poignée champignon et variateur de vitesse.', specs: { 'Tension': '18V', 'Course': '26 mm', 'Bois max': '135 mm', 'Poids': '2.5 kg' }, inStock: true, featured: false, image: img('DCS334', '#FFCC00') },
  { id: '22', name: 'PSB 420 EBQ Scie sauteuse Festool', brand: 'festool', category: 'Scies', price: 649, description: 'Scie sauteuse de précision avec guidage breveté et aspiration intégrée.', specs: { 'Puissance': '550W', 'Course': '26 mm', 'Bois max': '120 mm', 'Poids': '2.3 kg' }, inStock: true, featured: false, image: img('PSB420', '#14532d') },
  { id: '23', name: 'DJR187 Scie sabre 18V LXT', brand: 'makita', category: 'Scies', price: 319, description: 'Scie sabre brushless avec variateur de vitesse et mode orbital pour la démolition.', specs: { 'Tension': '18V', 'Course': '32 mm', 'Bois max': '255 mm', 'Poids': '3.5 kg' }, inStock: true, featured: false, image: img('DJR187', '#00A7E1') },
  { id: '24', name: 'DCS388 Scie sabre FLEXVOLT', brand: 'dewalt', category: 'Scies', price: 389, description: 'Scie sabre 54V pour les applications les plus lourdes en démolition et plomberie.', specs: { 'Tension': '54V', 'Course': '28.6 mm', 'Vitesse': '3000 courses/min', 'Poids': '3.4 kg' }, inStock: true, featured: false, image: img('DCS388', '#FFCC00') },
  { id: '25', name: 'HKC 55 Scie circulaire Festool', brand: 'festool', category: 'Scies', price: 689, oldPrice: 749, description: 'Scie circulaire sans fil 18V avec rail de guidage et aspiration des poussières.', specs: { 'Lame': '160 mm', 'Tension': '18V', 'Profondeur': '55 mm', 'Poids': '4.2 kg' }, inStock: true, featured: false, image: img('HKC55', '#14532d') },

  // ���─ Outillage à main ──
  { id: '26', name: 'Jeu de clés mixtes 440 (8-19mm)', brand: 'facom', category: 'Outillage à main', price: 149, description: 'Jeu de 12 clés mixtes Facom en acier chrome-vanadium avec finition satinée OGV.', specs: { 'Pièces': '12', 'Tailles': '8-19 mm', 'Finition': 'Satinée', 'Matériau': 'Chrome-Vanadium' }, inStock: true, featured: true, image: img('Facom+440', '#E63946') },
  { id: '27', name: 'Coffret douilles 1/2" S.161', brand: 'facom', category: 'Outillage à main', price: 399, oldPrice: 459, description: 'Coffret complet de 38 pièces en douilles 1/2" avec cliquet rotatif 72 dents.', specs: { 'Pièces': '38', 'Carré': '1/2"', 'Cliquet': '72 dents', 'Coffret': 'ABS renforcé' }, inStock: true, featured: true, image: img('Facom+S161', '#E63946') },
  { id: '28', name: 'Kraftform Kompakt 100 Tournevis', brand: 'wera', category: 'Outillage à main', price: 89, description: 'Set de tournevis Kraftform avec manche ergonomique multi-composants et lames interchangeables.', specs: { 'Pièces': '52', 'Types': 'PH/PZ/TX/HEX/Fente', 'Manche': 'Kraftform', 'Rangement': 'Pochette textile' }, inStock: true, featured: false, image: img('Wera+KF100', '#78BE20') },
  { id: '29', name: 'Tool-Check Plus Cliquet-tournevis', brand: 'wera', category: 'Outillage à main', price: 69, description: 'Kit compact cliquet-tournevis avec 39 embouts et douilles pour une utilisation universelle.', specs: { 'Pièces': '39', 'Cliquet': 'Zyklop Mini', 'Embouts': 'Impaktor', 'Rangement': 'Pochette compacte' }, inStock: true, featured: true, image: img('Wera+TCP', '#78BE20') },
  { id: '30', name: 'Joker Jeu de clés à cliquet', brand: 'wera', category: 'Outillage à main', price: 179, description: 'Jeu de 11 clés à cliquet combinées avec système anti-glissement et maintien de la vis.', specs: { 'Pièces': '11', 'Tailles': '8-19 mm', 'Cliquet': 'Intégré', 'Système': 'Anti-glissement' }, inStock: true, featured: false, image: img('Wera+Joker', '#78BE20') },
  { id: '31', name: 'Coffret FatMax Tournevis', brand: 'stanley', category: 'Outillage à main', price: 59, description: 'Set de 12 tournevis FatMax avec pointe noire diamant pour un grip maximal dans la vis.', specs: { 'Pièces': '12', 'Types': 'PH/PZ/Fente', 'Manche': 'Bi-matière', 'Pointe': 'Diamant' }, inStock: true, featured: false, image: img('Stanley+FM', '#FFC107') },
  { id: '32', name: 'Pinces Facom série CPE', brand: 'facom', category: 'Outillage à main', price: 119, description: 'Jeu de 4 pinces professionnelles : universelle, coupante, bec long et multiprise.', specs: { 'Pièces': '4', 'Types': 'Univ/Coup/Bec/Multi', 'Finition': 'Gainage bi-matière', 'Matériau': 'Acier C70' }, inStock: true, featured: false, image: img('Facom+CPE', '#E63946') },
  { id: '33', name: 'FatMax Cutter 25mm', brand: 'stanley', category: 'Outillage à main', price: 29, description: 'Cutter professionnel FatMax avec lame rétractable 25mm et corps bi-matière antidérapant.', specs: { 'Lame': '25 mm', 'Type': 'Rétractable', 'Corps': 'Bi-matière', 'Système': 'Blade Armor' }, inStock: true, featured: false, image: img('Stanley+Cut', '#FFC107') },
  { id: '34', name: 'Clé à molette Facom 250mm', brand: 'facom', category: 'Outillage à main', price: 49, description: 'Clé à molette chromée 250mm avec ouverture fine et mâchoires parallèles de précision.', specs: { 'Longueur': '250 mm', 'Ouverture max': '34 mm', 'Finition': 'Chromée', 'Mâchoires': 'Parallèles' }, inStock: true, featured: false, image: img('Facom+Mol', '#E63946') },

  // ── Mesure / Niveau ──
  { id: '35', name: 'Type 196-2 Niveau 120cm', brand: 'stabila', category: 'Mesure / Niveau', price: 89, description: 'Niveau à bulle professionnel 120cm avec 2 fioles et profil en aluminium renforcé.', specs: { 'Longueur': '120 cm', 'Fioles': '2', 'Précision': '0.5 mm/m', 'Matériau': 'Aluminium' }, inStock: true, featured: true, image: img('Stabila+196', '#FFD700') },
  { id: '36', name: 'Type 196-2 Niveau 60cm', brand: 'stabila', category: 'Mesure / Niveau', price: 59, description: 'Niveau à bulle compact 60cm pour les travaux courants de maçonnerie et menuiserie.', specs: { 'Longueur': '60 cm', 'Fioles': '2', 'Précision': '0.5 mm/m', 'Matériau': 'Aluminium' }, inStock: true, featured: false, image: img('Stabila+60', '#FFD700') },
  { id: '37', name: 'Type 80 AS Niveau 200cm', brand: 'stabila', category: 'Mesure / Niveau', price: 119, oldPrice: 139, description: 'Niveau professionnel 200cm avec profil en I pour une rigidité maximale sur les longues portées.', specs: { 'Longueur': '200 cm', 'Fioles': '2', 'Précision': '0.5 mm/m', 'Profil': 'I-beam' }, inStock: true, featured: false, image: img('Stabila+80', '#FFD700') },
  { id: '38', name: 'Laser rotatif LAR 160 G', brand: 'stabila', category: 'Mesure / Niveau', price: 899, description: 'Laser rotatif vert avec récepteur. Portée 800m en mode récepteur pour les grands chantiers.', specs: { 'Portée': '800 m (récepteur)', 'Couleur': 'Vert', 'Précision': '±1 mm/10m', 'IP': '65' }, inStock: true, featured: false, image: img('LAR160G', '#FFD700') },
  { id: '39', name: 'FatMax Mètre 8m', brand: 'stanley', category: 'Mesure / Niveau', price: 29, description: 'Mètre ruban 8m FatMax avec lame Blade Armor extra-large 32mm et crochet magnétique.', specs: { 'Longueur': '8 m', 'Largeur lame': '32 mm', 'Crochet': 'Magnétique', 'Revêtement': 'Blade Armor' }, inStock: true, featured: false, image: img('FatMax+8m', '#FFC107') },
  { id: '40', name: 'FatMax Mètre 5m', brand: 'stanley', category: 'Mesure / Niveau', price: 22, description: 'Mètre ruban compact 5m pour une utilisation quotidienne avec boîtier antichoc.', specs: { 'Longueur': '5 m', 'Largeur lame': '25 mm', 'Boîtier': 'ABS antichoc', 'Revêtement': 'Nylon' }, inStock: true, featured: false, image: img('FatMax+5m', '#FFC107') },
  { id: '41', name: 'Télémètre laser TLM165', brand: 'stanley', category: 'Mesure / Niveau', price: 139, description: 'Télémètre laser 50m avec calcul de surface, volume et fonction Pythagore.', specs: { 'Portée': '50 m', 'Précision': '±1.5 mm', 'Fonctions': 'Surface/Volume/Pythagore', 'IP': '54' }, inStock: true, featured: false, image: img('TLM165', '#FFC107') },
  { id: '42', name: 'Type 70 Niveau de poche', brand: 'stabila', category: 'Mesure / Niveau', price: 19, description: 'Niveau de poche magnétique 10cm pour les contrôles rapides de niveau et aplomb.', specs: { 'Longueur': '10 cm', 'Fioles': '1', 'Aimant': 'Terres rares', 'Matériau': 'Aluminium' }, inStock: true, featured: false, image: img('Stabila+70', '#FFD700') },

  // ── Accessoires ──
  { id: '43', name: 'Batterie 18V 5.0Ah XR', brand: 'dewalt', category: 'Accessoires', price: 99, oldPrice: 119, description: 'Batterie lithium-ion 18V 5.0Ah compatible avec toute la gamme XR DeWALT.', specs: { 'Tension': '18V', 'Capacité': '5.0 Ah', 'Type': 'Li-Ion', 'Indicateur': 'LED 3 niveaux' }, inStock: true, featured: true, image: img('DCB184', '#FFCC00') },
  { id: '44', name: 'Batterie M18 HB12 High Output 12Ah', brand: 'milwaukee', category: 'Accessoires', price: 199, oldPrice: 229, description: 'Batterie haute capacité 12.0Ah pour les applications les plus énergivores du système M18.', specs: { 'Tension': '18V', 'Capacité': '12.0 Ah', 'Type': 'High Output', 'Indicateur': 'LED 4 niveaux' }, inStock: true, featured: true, image: img('M18+HB12', '#DB0032') },
  { id: '45', name: 'Batterie 18V 6.0Ah LXT', brand: 'makita', category: 'Accessoires', price: 109, description: 'Batterie lithium-ion 18V 6.0Ah avec indicateur de charge LED et protection contre la surcharge.', specs: { 'Tension': '18V', 'Capacité': '6.0 Ah', 'Type': 'Li-Ion LXT', 'Indicateur': 'LED' }, inStock: true, featured: false, image: img('BL1860B', '#00A7E1') },
  { id: '46', name: 'Chargeur rapide DCB118 FLEXVOLT', brand: 'dewalt', category: 'Accessoires', price: 79, description: 'Chargeur rapide compatible 18V/54V FLEXVOLT. Charge une 5.0Ah en 35 minutes.', specs: { 'Compatibilité': '18V / 54V', 'Temps de charge': '35 min (5Ah)', 'Ventilateur': 'Oui', 'Diagnostic': 'LED' }, inStock: true, featured: false, image: img('DCB118', '#FFCC00') },
  { id: '47', name: 'Coffret TSTAK DeWALT', brand: 'dewalt', category: 'Accessoires', price: 49, description: 'Coffret de transport modulaire TSTAK empilable et interconnectable.', specs: { 'Dimensions': '440x332x145 mm', 'Matériau': 'Polypropylène', 'Système': 'TSTAK', 'Fermetures': '2 latérales' }, inStock: true, featured: false, image: img('TSTAK', '#FFCC00') },
  { id: '48', name: 'Coffret PACKOUT Milwaukee', brand: 'milwaukee', category: 'Accessoires', price: 69, oldPrice: 79, description: 'Coffret modulaire PACKOUT résistant aux chocs avec mousse personnalisable.', specs: { 'Dimensions': '500x380x170 mm', 'Matériau': 'Polymère renforcé', 'Système': 'PACKOUT', 'Résistance': 'IP65' }, inStock: true, featured: false, image: img('PACKOUT', '#DB0032') },
  { id: '49', name: 'Coffret MAKPAC Type 3', brand: 'makita', category: 'Accessoires', price: 39, description: 'Coffret empilable MAKPAC compatible avec le système Festool Systainer.', specs: { 'Dimensions': '395x295x210 mm', 'Matériau': 'ABS', 'Système': 'MAKPAC', 'Compatible': 'Systainer' }, inStock: true, featured: false, image: img('MAKPAC3', '#00A7E1') },
  { id: '50', name: 'Chargeur rapide M18/M12', brand: 'milwaukee', category: 'Accessoires', price: 69, description: 'Chargeur double compatible M12 et M18 avec indicateur de diagnostic avancé.', specs: { 'Compatibilité': 'M12 / M18', 'Temps de charge': '30 min (5Ah)', 'Ventilateur': 'Oui', 'Ports': '1' }, inStock: true, featured: false, image: img('Chargeur+M18', '#DB0032') },
  { id: '51', name: 'Set embouts Impact 32 pièces', brand: 'dewalt', category: 'Accessoires', price: 35, description: 'Coffret de 32 embouts Impact Torsion pour visseuses à chocs avec porte-embout magnétique.', specs: { 'Pièces': '32', 'Types': 'PH/PZ/TX', 'Porte-embout': 'Magnétique', 'Résistance': 'Impact Torsion' }, inStock: true, featured: false, image: img('DT70523', '#FFCC00') },
  { id: '52', name: 'Set forêts SDS-Plus 10 pièces', brand: 'dewalt', category: 'Accessoires', price: 45, description: 'Set de 10 forets SDS-Plus Extreme pour perforateur. Béton, brique et pierre.', specs: { 'Pièces': '10', 'Diamètres': '5-12 mm', 'Type': 'SDS-Plus', 'Matériau': 'Carbure' }, inStock: true, featured: false, image: img('SDS+Set', '#FFCC00') },
  { id: '53', name: 'Chargeur rapide DC18RC', brand: 'makita', category: 'Accessoires', price: 59, description: 'Chargeur rapide Makita pour batteries LXT 14.4V et 18V avec ventilateur de refroidissement.', specs: { 'Compatibilité': '14.4V / 18V LXT', 'Temps de charge': '45 min (5Ah)', 'Ventilateur': 'Oui', 'Indicateur': 'LED tricolore' }, inStock: true, featured: false, image: img('DC18RC', '#00A7E1') },
  { id: '54', name: 'Lames scie circulaire Festool W48', brand: 'festool', category: 'Accessoires', price: 59, description: 'Lame de scie circulaire 48 dents pour coupes fines dans le bois massif et les panneaux.', specs: { 'Diamètre': '160 mm', 'Dents': '48', 'Alésage': '20 mm', 'Application': 'Bois fin' }, inStock: true, featured: false, image: img('W48+Festool', '#14532d') },
]
